### PR TITLE
feat: fetch data from postgrest, update firebase

### PR DESCRIPTION
**Pull request by clintonlunn**

### CODE REVIEW

**Comment by marshallrobinson** [comment]
Thanks folks, Mackenzie and I will review this in the next week.

**Comment by Mackenzie-Cope** [comment]
Marshall/Mackenzie comments:
Disclaimer: all of these comments are strictly differences between the live application and Firebase version.

**Info sidebar**
1. Some sites are not showing the about info or image above the graph (ex: P1094 and others)
2. Some sites do not have download options under graphs after selecting a site without a graph. See theory below.
THEORY - Selecting a point with no graph data (AE-FW1) then selecting a site WITH graph data (PW07B) = download buttons disappear. If you then click on a site with Notes (P1001), the download options come back. See screenshot attached.
image
3. The graphs are showing multiple points per day, and only need one per day to make the graph clearer. Current version shows one per day (can compare using PW20). Showing more than one per day makes graphs look weird.

**Map**
1. Site area polygons are not visible on the map

**Search**
1. Site area name search has no results

@lance-weaver @jjhi11 @clintonlunn

**Comment by marshallrobinson** [comment]
All of the fixes look great, nice work. One (hopefully minor) comment to address:
-Springs/wells with no graph data show the download data option, when the download data option needs to be hidden.
image

**Comment by marshallrobinson** [comment]
> All of the fixes look great, nice work. One (hopefully minor) comment to address: -Springs/wells with no graph data show the download data option, when the download data option needs to be hidden. image

@lance-weaver @jjhi11 are the "Download Elevation Data Output" (see screenshot) able to be removed from popups that do not have graph data?

**Comment by lance-weaver** [comment]
I'm finding a serious error.  And it existed in the original application but is now even worse.

When you do a advanced search... for something like "spring" or well, that gives many results in the results window.  And then click on one of them.  It returns a blank result.  Which at first you might think that site has no pic or something. But Its actually an error in the query.

**Comment by jjhi11** [comment]
> I'm finding a serious error. And it existed in the original application but is now even worse.
> 
> When you do a advanced search... for something like "spring" or well, that gives many results in the results window. And then click on one of them. It returns a blank result. Which at first you might think that site has no pic or something. But Its actually an error in the query.
> 
> Cant really figure it out yet. but working on it.

Im guessing it is related to the display = 1 def expression?  Maybe? Not sure why only sites with the field of display equalling 1 are supposed to shown.

**Comment by lance-weaver** [comment]
Is it possible that not a single well has any note or graph data?

**Comment by jjhi11** [comment]
> Is it possible that not a single well has any note or graph data?

Oh i think so. I do remember looking that up initially. There were like farm wells or something that didnt seem as relevant and those had no data.

**Comment by Mackenzie-Cope** [comment]
Updates are looking good! Marshall and I found a few new comments.

1. On certain sites there are no images or additional data showing. Only shows the graph and download options. (EX: W-2, Callao C119)
2. Polygons have tiny labels that should be removed (Jay may have already commented this out)
3. Springs with notes and a graph are
a) Missing download options, and
b) switching between daily/monthly toggles makes the graph disappear.
4. Advanced search still searches all points, even hidden ones, and serves them as selectable results.
- possibly needs better logic for the search or updates to the layer definition
5. Popups for the hidden points (EX: Panguitch well) shows the graph and download for the last point selected.

**Comment by jjhi11** [comment]
Im not seeing the labels for the site areas on the preview link or on my local dev server

**Review by marshallrobinson — APPROVED** [review]

**Pull request merged**
